config/routes.rb
Rails.application.routes.draw do
  get 'reviews_controller/new'
  get 'reviews_controller/create'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cars do
    resources :reservations, only:[:create]
  end


  resources :reservations, only:[:index, :show, :edit, :update, :destroy] do
      resources :reviews, only:[:create]
  end
  # VERB PATH, to: "CONTROLLER#ACTION", as: "PREFIX"
  get "search", to: "cars#search", as: "search"
  # get "reviews/:id", to: "reviews#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations
  has_many :reviews, dependent: :destroy
  CATEGORIES = ["Classic", "Convertible", "Coupe", "Exotic", "Sedan", "SUV", "Sport"]
  validates :model, :brand, :year, :category, :description, :photo, :location, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :end_day, presence: true
  validates :price, presence: true
  validates :starting_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  belongs_to :user

  validate :user_booked_the_car
  validates :content, presence: true

  private

  def user_booked_the_car
    unless user.reservations.where(car: car).any?
      errors.add(:user, 'has not booked this car')
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  skip_after_action :verify_authorized, only: :search
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  def index
    @cars = policy_scope(Car).where(owner: current_user)
  end

  def show
    @reservation = Reservation.new
  end

  def new
    @car = Car.new
    authorize @car
  end

  def create
    @car = current_user.cars.new(car_params)
    authorize @car
    if @car.save
      redirect_to cars_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @car.update(car_params)
      redirect_to cars_path
    else
      render :edit
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  def search
    @cars = policy_scope(Car).where(category: params["search"]["query"])

    @cars = Car.geocoded

    @markers = @cars.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { car: car })
      }
    end
  end

  private

  def car_params
    params.require(:car).permit(:model, :year, :brand, :category, :description, :location, :photo, :price)
  end

  def set_car
    @car = Car.find(params[:id])
    authorize @car
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @cars = Car.all
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def new
    @reservation = Reservation.new
    authorize @reservation
  end

  def create
    @reservation = current_user.reservations.new(reservation_params)
    @reservation.car = Car.find(params[:car_id])
    authorize @reservation

    if @reservation.save
      redirect_to reservations_path
    else
      render :new
    end
  end

  def index
    @reservations = policy_scope(Reservation)
    @markers = @reservations.map do |reservation|
      {
        lat: reservation.car.latitude,
        lng: reservation.car.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { reservation: reservation }),
        image_url: helpers.asset_url(reservation.car.photo)
      }
    end
  end

  def show
    @review = Review.new
    @markers = [{
      lat: @reservation.car.latitude,
      lng: @reservation.car.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { reservation: @reservation })
    }]
    authorize @reservation
  end

  def destroy
    @reservation.destroy
    redirect_to reservations_path
    authorize @reservation
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to reservations_path
    else
      render :edit
    end
  end

  private

  def reservation_params
    params.require(:reservation).permit(:starting_date, :end_day, :price, :days)
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
    authorize @reservation
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @car = Car.find(params[:car_id])
    @review = Review.new
    authorize @review
  end

  def create
    @reservation = Reservation.find(params[:reservation_id])
    @review = current_user.reviews.build(review_params)
    @review.car = @reservation.car
    if @review.save!
      flash[:success] = "Thanks for your review!"
      redirect_to car_path(@reservation.car)
    else
      render 'reservations/show'
    end
    authorize @review
  end

private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/_car-card.html.erb
<%= link_to car_path(car), class:"car-card" do %>
  <div class="card-trip">
    <%= cl_image_tag car.photo, alt: "alttext", height: 200, width: 250, crop: :fill, class: "w-100"%>
    <div class="card-trip-infos">
      <div>
        <h2><%= car.brand.upcase %></h2>
        <p><%= car.model %></p>
      </div>
      <h2 class="card-trip-pricing">$<%= car.price %> </h2>
    </div>
  </div>
<% end %>

app/views/cars/_info_window.html.erb
<%= cl_image_tag car.photo , height:150, width: 200 %>
<h4><%= car.brand %> - <%= car.model %></h4>
<p><%= car.location %></p>

app/views/cars/edit.html.erb
<div class="banner-2 mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1434187008486-2768576189ee?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80)">
  <div class="container">
    <h1><strong>Edit your car</strong></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
          <%= simple_form_for @car do |f| %>
          <%= f.input :model, label: false, placeholder:"BMW" %>
          <%= f.input :brand, label: false, placeholder:"X3" %>
          <%= f.input :year, label: false,placeholder:"2016" %>
          <%= f.input :category, label: false,collection: Car::CATEGORIES %>
          <%= f.input :description, label: false,placeholder:"The BMW X3 is a compact luxury crossover SUV manufactured by German automaker BMW since 2003." %>
          <%= f.input :location, label: false, placeholder:"Madrid" %>
          <%= f.input :price, label: false, placeholder:"$250" %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <div class="container mx-auto my-3">
            <%= f.submit "Edit car", class: "btn btn-danger" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cars/index.html.erb
<div class="container cars-wrapper">
  <div class="row">
    <% @cars.each do |car| %>
    <div class="col-12 col-lg-6">
      <div class="card-product mt-3 mb-3">
        <%= cl_image_tag(car.photo, crop: :fill) %>
        <div class="card-product-infos m-1">
          <h4><strong><%= car.brand %></strong> - <%= car.model %></h4>
          <p class="mt-4"><strong>Model year: </strong><%= car.year %></p>
          <p class="mt-2"><strong>Category: </strong><%= car.category %></p>
          <p class="mt-2"><strong>Description: </strong><%= truncate(car.description, length: 20,separator: ' ') %></p>
          <p class="mt-2"><strong>Location: </strong><%= car.location %></p>
          <p class="my-2"><strong>Price: </strong> $<%= car.price %></p>
          <div class="d-flex justify-content-around">
            <% if policy(car).edit? %>
            <%= link_to "Update", edit_car_path(car) %>
            <% end %>
            <% if policy(car).destroy? %>
            <%= link_to car_path(car), method: :delete, data: {confirm: 'Are you sure?'} do %>
            <i class="fas fa-trash"></i>
            <% end %>
            <% end  %>
          </div>
        </div>
      </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="banner-2" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1434187008486-2768576189ee?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80)">
  <div class="container">
    <h1>Add your car</h1>
    <h2>Rent your car and start to earn money</h2>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= simple_form_for @car do |f| %>
        <%= f.input :model, label: false, placeholder:"BMW" %>
        <%= f.input :brand, label: false, placeholder:"X3" %>
        <%= f.input :year,label: false, placeholder:"2016" %>
        <%= f.input :category, collection: Car::CATEGORIES,label: false, placeholder:"Category" %>
        <%= f.input :description, label: false, placeholder:"The BMW X3 is a compact luxury crossover SUV manufactured by German automaker BMW since 2003."  %>
        <%= f.input :location, label: false, placeholder:"Madrid" %>
        <%= f.input :price, label: false, placeholder:"$250" %>
        <%= f.input :photo, label: false  %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="container mx-auto my-3">
          <%= f.submit  "Add a car", class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/cars/search.html.erb
<div class="main-container-search">
  <div class="cards-search mt-2">

    <% @cars.each do |car| %>
    <%= link_to car_path(car), class:"card-search-wrapper" do %>
    <div class="card-search my-2 mx-3">
      <%= cl_image_tag(car.photo, width: 500, height: 600, crop: :fill) %>
      <div class="card-search-infos">
        <h2> <%= car.brand %> - <%= car.model %></h2>
        <p><strong>Category: </strong><%= car.category %></p>
        <p><strong>Description </strong><%= truncate(car.description, length: 100,separator: ' ') %></p>
        <p><strong>Location: </strong><%= car.location %></p>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>

  <div
  id="map"
  style="width: 550px;
  height: 600px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

  </div>

</div>

app/views/cars/show.html.erb
<div class="banner mb-5" id="" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @car.photo %>);">
</div>

<div class="container car-reservation">
  <div class="row">
    <div class="col-md-8">
      <h1 class="mb-3"><%= @car.model %><strong> <%= @car.brand %></strong></h1>
      <div class="mb-5 d-flex justify-content-around">
        <div>
          <p><i class="fas fa-user"></i> 4 passengers</p>
        </div>
        <div>
          <p><i class="fas fa-suitcase"></i> 3 suitcases</p>
        </div>
        <div>
          <p><i class="fas fa-car"></i> Automatic</p>
        </div>
      </div>
      <p><%= @car.description %></p>

      <div class="reviews">

        <% @car.reviews.order(updated_at: :desc).each do |review| %>
        <div class="card my-3">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-12 col-lg-3 d-flex align-items-center">
                <img src="https://www.classifapp.com/wp-content/uploads/2017/09/avatar-placeholder.png" class="img-rounded">
                <div style="padding-left: 10px">
                <span class="review-block-name"><a><strong><%= /(?<user>.*)@/.match(review.user.email)[:user] %></strong></a></span>
                <p class="review-block-date" style="margin-bottom:0; font-size: 13px"><%= review.created_at.strftime("%B %Y") %></p>
                </div>
              </div>
              <div class="col-sm-12">
                <div class="review-block-title"></div>
                <div class="review-block-description"><%= review.content %></div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="car-booking">
        <h5 class="mb-3">Reservation</h5>
        <h4>$ <span id="that-car-price"><%= @car.price %></span> /day</h4>
        <%= simple_form_for [@car, @reservation] do |f| %>
        <%= f.input :starting_date, as: :string, input_html: { class: "datepicker", id: "start_date" } %>
        <%= f.input :end_day, as: :string, input_html: { class: "datepicker", id: "end_date" } %>
        <%= f.hidden_field :price, value:0, id: "price-setter" %>
        <%= f.hidden_field :days, value:0, id: "days-setter" %>
        <div>
          <div class="d-flex justify-content-between">
            <div>
              <p>Days of renting:</p>
            </div>
            <div>
              <p> <span id="days">0</span></p>
            </div>
          </div>
        </div>
        <div class="cost-style text-white">
          <div class="d-flex justify-content-between">
            <div>
              <p>Total cost:</p>
            </div>
            <div class="">
              <p>$<span id="total-price">0</span></p>
            </div>
          </div>
        </div>
        <%= f.button :submit, class: "btn btn-primary mt-5 btn-block" %>
        <% end %>

      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span class="mr-5"><strong>Yay!</strong> 🎉 Make your dream happen! Drive the <strong> <%= @car.brand %> <%= @car.model %> </strong></span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
  </head>
  <body>
    <%= render 'components/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'components/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<header>
  <div class="overlay"></div>
  <%= cl_video_tag "Carvideo2_xwmbee", autoplay: true, muted: true, loop: true %>
<!--   <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="https://gcs-vimeo.akamaized.net/exp=1572484013~acl=%2A%2F473935215.mp4%2A~hmac=42345892521e61ccd4192b274affeeaeec4b71d196f7d3dd03f6a88680893b95/vimeo-prod-skyfire-std-us/01/740/6/153703075/473935215.mp4" type="video/mp4">
    </video> -->
    <div class="container h-100">
      <div class="d-flex h-100 text-center align-items-center">
        <div class="w-100 text-white">
          <h1 class="display-3 text-white">Your best option</h1>
          <p class="lead mb-0 text-dark"></p>
          <%= simple_form_for :search, url: search_path, method: :get do |f| %>
          <div class="search-form-control form-group w-50 mx-auto">
            <select class="form-control seleccano Gastón Lascano
Recently edited these files
Everyone else
￼
agusgrt required text-white" name="search[query]" id="search_query">
              <% Car::CATEGORIES.each do |category| %>
              <option value="<%= category %>"><%= category %></option>
              <% end %>
            </select>
          </div>
          <button name="button" type="submit" class="btn btn-danger btn-block btn-lg text-white w-50 mx-auto">
          Search cars! <i class="fas fa-search text-white"></i></button>
          <% end %>
        </div>
      </div>
    </div>
  </header>





  <div class="container mt-5">
    <div class="row">
      <% @cars.first(6).each do |car| %>
      <div class="col-sm-12 col-lg-4 col-md-6">
        <div class="my-3">
          <%= render "cars/car-card", car: car %>
        </div>
      </div>
      <% end %>
    </div>
  </div>



  <div class="container justify-content-space-between badge-light py-5" id="Nosotros">
    <h1 class="text-center my-5"><strong>Our team</strong></h1>
    <div class="row">
      <div class="col-sm-12 col-lg-3 text-center">
        <img class="rounded-circle" src="https://avatars2.githubusercontent.com/u/54599926?s=460&v=4" alt="Generic placeholder image" width="140" height="140">
        <h3 class="my-2">Gaspar Baldunciel</h3>
        <h3>CEO</h3>
        <a href="https://www.linkedin.com/in/gaspar-baldunciel-30b60a119" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
        <p class="mb-5">Profesional Rugby Player and entrepeneur. Owner of Clifftone brand.He joined Le Wagon on August 2019. Founder of Le Chauffeur.</p>
      </div>
      <div class="col-sm-12 col-lg-3 text-center">
        <img class="rounded-circle" src="https://avatars0.githubusercontent.com/u/54510877?s=460&v=4" alt="Generic placeholder image" width="140" height="140">
        <h3 class="my-2">Gastón Lascano</h3>
        <h3>CFO</h3>
        <a href="https://www.linkedin.com/in/gaston-lascano-77a932163" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
        <p class="mb-5">Management profesional and Wakeboard Rider. He joined Le Wagon on August 2019. Co-founder of Le Chauffeur.</p>
      </div>
      <div class="col-sm-12 col-lg-3 text-center">
        <img class="rounded-circle" src="https://avatars1.githubusercontent.com/u/54502513?s=460&v=4" alt="Generic placeholder image" width="140" height="140">
        <h3 class="my-2">Enzo Crivelli</h3>
        <h3>CMO</h3>
        <a href="https://www.linkedin.com/in/enzo-crivelli-5b3b6012a" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
        <p class="mb-5">Marketing professional and Triathlete. He joined Le Wagon August 2019. Co-founder of Le Chauffeur</p>
      </div>
      <div class="col-sm-12 col-lg-3 text-center">
        <img class="rounded-circle" src="https://avatars1.githubusercontent.com/u/54517348?s=460&v=4" alt="Generic placeholder image" width="140" height="140">
        <h3 class="my-2">Agustín Greissing </h3>
        <h3>Street sweeper</h3>
        <a href="https://www.linkedin.com/in/agustingreissing" target='_blank'><i class="fab fa-2x fa-linkedin"></i></a>
        <p class="mb-5">Economist. Passionate about reading and cooking. He joined Le Wagon on August 2019. Co-founder of Le Chauffeur.</p>
      </div>
    </div>
  </div>

app/views/reservations/_info_window.html.erb
<%= cl_image_tag reservation.car.photo , height:150, width: 200 %>
<h2><%= reservation.car.brand%> <%= reservation.car.model %></h2>

<p><%= reservation.car.location %></p>

app/views/reservations/_review_form.html.erb
<div class="container justify-content-center my-5">
<%= simple_form_for [@reservation, @review] do |f| %>
  <% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>
  <% end %>
  <%= f.input :content, label: false, placeholder: "Add a comment"%>
  <%= f.submit "Add a review", class: "btn btn-danger" %>
<% end %>
</div>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/edit.html.erb
<h1>Reservations#edit</h1>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-5">
      <h3 class="text-center">Reservations</h3>
      <% @reservations.each do |reservation| %>
        <%= link_to reservation_path(reservation), class:"card-search-wrapper" do %>
          <div class="card-search my-2 mx-3">
            <%= cl_image_tag(reservation.car.photo, width: 600, height: 700, crop: :fill) %>
            <div class="card-search-infos">
              <h2> <%= reservation.car.brand %> <%= reservation.car.model %></h2>
              <p><strong>Date Reservation: </strong><%= reservation.starting_date %></p>
              <p><strong>Days: </strong><%= reservation.days %></p>
              <p><strong>Location: </strong><%= reservation.car.location %></p>
              <p><strong>Price: </strong><%= reservation.price %></p>
                <% if policy(reservation).destroy? %>
                <%= link_to reservation_path(reservation), method: :delete, data: {confirm: 'Are you sure?'} do %>
                <i class="fas fa-trash"></i>
                <% end %>
                <% end  %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-7">
      <div
        id="map"
        style="width: 100%;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

app/views/reservations/new.html.erb
<h1>Reservations#new</h1>
<p>Find me in app/views/reservations/new.html.erb</p>

app/views/reservations/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div id="reservation-card" class="bg-white mt-2 p-4">
      <div class="mb-2">
        <h4 class="text-center mt-2">Your reservation</h4>
      </div>
      <div class="card w-100">
        <%= cl_image_tag(@reservation.car.photo, height:300, crop: "fill") %>
        <div class="card-body">
          <h5 class="card-title"><%= @reservation.car.model %><%= @reservation.car.brand %></h5>
          <p class="card-text">You are about to make your dream true. Reservation is done! <strong>Thanks for trusting us!</strong> </p>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item d-flex justify-content-between">
            <div>
              <p>Pick up day: </p>
            </div>
            <div>
              <p><strong><%= @reservation.starting_date %></strong></p>
            </div>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <div>
              <p>Drop up day: </p>
            </div>
            <div>
              <p><strong><%= @reservation.end_day %></strong></p>
            </div>
          </li>
          <li class="list-group-item d-flex justify-content-between">
            <div>
              <p>Total cost: </p>
            </div>
            <div>
              <p><strong><%= @reservation.car.price %></strong></p>
            </div>
          </li>
        </ul>
        <div class="card-body d-flex justify-content-between">
          <div>
            <a href="<%= reservations_path %> " class="card-link">My reservations</a>
          </div>
          <div>
            <a href="<%= car_path %> " class="card-link">My car</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-12">
     <div
     id="map"
     style="width: 100%;
     height: 800px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">

   </div>
 </div>
</div>
</div>

<%= render 'reservations/review_form' %>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>ReviewsController#create</h1>
<p>Find me in app/views/reviews_controller/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container justify-content-center my-5">
<%= simple_form_for [@car, @review] do |f| %>
  <% if @review.errors.any? %>
  <% @review.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>
  <% end %>
  <%= f.input :content, label: false, placeholder: "Add a comment"%>
  <%= f.submit "Add a review", class: "btn btn-danger" %>
<% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>